import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class Crash_3dce3f4278389205653e6b5539e71d4c0de5edfe {
    static final String base64Bytes = String.join("", "UlJSUlJSUlJSUlJSUlJSUlJSUlJSVURVRFVERERVRFVEVURVRERVRFVERERVRFVEVUREVURVRFVEVURVVURERERERFVVRFVEVVVEUlJSUlVEVURVREREVURVRFVSRFVERERVRFVERFVVRFVVVVVVVURVVURMVVVEVVVERFVEVURERFVEVURVUlVEVURSUlJEVVJSRERSUlJSUlJSUkxMTExMTExSUlJSUlJMTExSTExMTExSTExSUlJSUlJSUlJSUlJSUlJVRFVSUlJSUlJSUlJSUlJSUlJVRFVEVURERFVEVURVRFVERFVEVURERFVEVURVRERVRFVEVURVRFVVREREREREVVVEVURVVURSUlJSVURVRFVERERVRFVEVVJEVURERFVEVUREVVVEVVVVVVVVRFVVRExVVURVVUREVURVREREVURVRFVSVURVRFJSUkRVUlJERFJSUlJSUlJSTExMTExMTFJSUlJSUkxMTFJMTExMTFJMTFJSUlJSUlJSUlJSUlJSUlVEVVJSUlJEUlJSRERMTExMTExMTExMTERVREREVVJSRERSUlJSUlJSUlJSRFVSUlJSUlJSTExMTExMTFJSUlJSUkxMTFJMUlJMVURVUlVEVURVREREVURVVURVVURMVVVEVVVEVURVRERVRFVEVURVRFVERFVEVURERFVEUkRSVURVVURSUkRVRERSUlJSUlJSUlJSUlJSRFVSUkREUlJSUlJSUlJMTExMTExMUlJSUlJSTExMUkxMTExMUkxMUlJSUlJSUlJSUlJSUlJSVURVUlJSUkRSUlJERExMTExMTExMTExMRFVERERVUlJERFVEVURVRFVVRFVVRFVERERSUkRERFJSUlJSVURVRERSUlJSUlJSUlVEVURVUlJSUlJEUlJERFJSUlJSUlJSUlJSUlJSUlJSUlVEVURVVVVEVVVETERSUlJSUlVVVURVVUREVURVREREVURVRFVVRFVERERVRFVEVURVUlVVVVVVVVVVUlJSUlVSUlJSUkRVUlJSUlJSUkxMTExMTExSUlJSUlJMTExSTFJSTExSRERVTFVVTFJSUkREVVVSUlJSUlJSUlJSVURVRFVERERVRFVEVURVRERVRFVERERVRFVEVUREVURVRFVEVURVVURERERERFVVRFVEVVVEUlJSUlVEVURVREREVURVRFVSRFVERERVRFVERFVVRFVVVVVVVURVVURMVVJSRFJSUkRETExMTExMTExMTExEVURERFVSUkREUlJSUlJSUlJSUkRVUlJSUlJSUkxMTExMTExSUlJSUlJMTExSTFJSTFVEVVJVRFVEVURERFVEVVVEVVVETFVVRFVVRFVEVUREVURVRFVEVURVRERVRFVERERVRFJSUkxMTExMTExSUlJSUlJSUlJSRFVEVURERFVEVVVEVUREVURVREREVURVRFJSUlJSUlJSUlJSUlJSRERERFJSUlJVRFVEVURERFVEVURVRExMTFJMVVVEVVVERFVEVURERFVEVURVUlVEVURSUlJEVVJSRERSUlJSUlJSUkxMTExMTExSUlJSUlJMTExSTExMTExSTExSUlJSUlJSUlJSUlJSUlJVRFVSUlJSRFJSUkRETExMTExMTExMTExEVURERFVSUkREUlJSUlJSUlJSUkRVUlJSUlJSUkxMTExMTExSUlJSUlJMTExSTFJSTFVEVVJVRFVEVURERFVEVVVEVVVETFVVRFVVRFVEVUREVURVRFVEVURVRERVRFVERERVRFJEUlVEVVVEUlJEVUREUlJSUlJSUlJSUlJSUkRVUlJERFJSUlJSUlJSTExMTExMTFJSUlJSUkxMTFJMTExMTFJMTFJSUlJSUlJSUlJSUlJSUlVEVVJSUlJEUlJSRERMTExMTExMTExMTERVREREVVJSRERVRFVEVURVVURVVURVREREUlJERERSUlJSUlVEVUREUlJSUlJSUlJVRFVEVVJSUlJSRFJSRERSUlJSUlJSUlJSUlJSUlJSUlJVRFVEVVVVRFVVRExEUlJSUlJVVVVEVVVERFVEVURERFVEVURVVURVREREVURVRFVEVVJVVVVVVVVVVVJSUlJVUlJSUlJEVVJSUlJSUlJMTExMTExMUlJSUlJSTExMUkxSUkxMUkREVUxVVUxSUlJERFVVUlJSUlJSUlJSUlVEVURVREREVURVRFVEVUREVURVREREVURVRFVERFVEVURVRFVEVVVERERERERVVURVRFVVRFJSUlJVRFVEVURERFVEVURVUlVVTFJSUkREVVVSUlVEREREVURVRFVVUkQ=");

    public static void main(String[] args) throws Throwable {
        Crash_3dce3f4278389205653e6b5539e71d4c0de5edfe.class.getClassLoader().setDefaultAssertionStatus(true);
        try {
            Method fuzzerInitialize = MazeFuzzer.class.getMethod("fuzzerInitialize");
            fuzzerInitialize.invoke(null);
        } catch (NoSuchMethodException ignored) {
            try {
                Method fuzzerInitialize = MazeFuzzer.class.getMethod("fuzzerInitialize", String[].class);
                fuzzerInitialize.invoke(null, (Object) args);
            } catch (NoSuchMethodException ignored1) {
            } catch (IllegalAccessException | InvocationTargetException e) {
                e.printStackTrace();
                System.exit(1);
            }
        } catch (IllegalAccessException | InvocationTargetException e) {
            e.printStackTrace();
            System.exit(1);
        }
        byte[] input = java.util.Base64.getDecoder().decode(base64Bytes);
        MazeFuzzer.fuzzerTestOneInput(input);
    }
}